#!/bin/sh

echo "🔍 Running pre-commit hook..."

# 테스트 실행
./gradlew test || {
    printf "\e[31m❌ Tests failed! Fix the issues before committing.\e[0m\n";
    exit 1;
}

# 코드 스타일 검사 (자동 수정 없음)
./gradlew spotlessCheck || {
    printf "\e[31m❌ Spotless check failed! './gradlew spotlessApply'명령어를 실행하고 sptless가 적용된 파일들을 다시 add 후 commit해주세요.\e[0m\n";
    exit 1;
}

# 프로젝트 빌드 수행
./gradlew build || {
    printf "\e[31m❌ Build failed! Fix the issues before committing.\e[0m\n";
    exit 1;
}

printf "\e[32m✅ pre-commit checks passed!\e[0m\n"
exit 0
