# 데이터베이스 설정
spring:
    datasource:
        url: jdbc:postgresql://ktb-9team.cf8giy2ka0f5.ap-northeast-2.rds.amazonaws.com:9465/postgres
        username: postgres
        password: ov9qHJs5495WuS2Oypn3

    # 카카오 OAuth2 설정
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: e3adecc7a9d48969bcf943f560b4fef3
                        client-secret: eBsCVF6eEdi108k5hutkG1RsY2FMys7d
                        redirect-uri: "{baseUrl}/login/oauth2/code/kakao"

    # JWT 보안 설정
    jwt:
        secret: RnQVviMQrMO8w9GZRrHUNZjSwMAfqBNmxPWFMITJZB8=

    # 활성 프로필 설정
    profiles:
        active: local

    # Redis 데이터베이스 설정
    data:
        redis:
            host: redis-master.redis.svc.cluster.local
            port: 6379
            password: Cm4iusz0qC

# Sentry 에러 추적 설정
sentry:
    dsn: https://26b9c9761749a6802bd4ee93b0a5fe76@o4509093603639296.ingest.us.sentry.io/4509093604753408
    # 사용자 PII 정보 전송 여부
    send-default-pii: true
    # 트레이스 샘플링 비율 (1.0 = 100%)
    traces-sample-rate: 1.0
    org: warab
    projectName: java-spring-boot
    authToken: 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

# OAuth2 로그인 후 리다이렉션 URL
redirect:
    oauth2:
        after:
            login: http://localhost:3000/info

# CORS 설정
cors:
    allowed-origin: http://localhost:3000
