# 서비스명
spring:
  application:
    name: warab

  config:
    import: application-secrets.yml
  # 카카오 OAuth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # DB
  datasource:
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      # Query
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    # debug
    #show-sql: true
    #properties:
    #  hibernate:
    #    format_sql: true

  # session -> redis
  session:
    store-type: redis

# Netty
io:
  netty:
    resolver:
      dnsResolver: default

# DEBUG
logging:
  level:
    org:
      springframework:
        security:
          oauth2:
            client: DEBUG
            core: DEBUG
    # logging.level.org.hibernate.SQL=DEBUG
    # logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Cookie
server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: true
        domain: warab.store
  forward-headers-strategy: framework
