openapi: 3.0.0
info:
  title: User API
  description: 유저 관련 API (프로필 조회 및 닉네임 중복 확인)
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /users/profile/{user_id}:
    get:
      summary: 유저 프로필 조회 API
      description: 특정 유저의 프로필 정보를 조회합니다.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 12345
          description: 조회할 유저의 ID
      responses:
        "200":
          description: 유저 프로필 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "user_profile_inquiry success"
                  data:
                    type: object
                    properties:
                      nickname:
                        type: string
                        example: "player01"
                      discord_link:
                        type: string
                        example: "https://discord.gg/HhjFGsgb"
        "401":
          description: 잘못된 요청 (user_id가 숫자가 아니거나 0 이하)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "invalid_user_id"
                  data:
                    type: object
                    properties:
                      result:
                        type: boolean
                        example: false
        "403":
          description: 권한 부족
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "required_permission"
                  data:
                    type: object
                    nullable: true

  /users/check_nickname:
    get:
      summary: 닉네임 중복 확인 API
      description: 유저가 닉네임을 변경할 때 중복 여부를 확인합니다.
      parameters:
        - name: nickname
          in: query
          required: true
          schema:
            type: string
            example: "NewPlayer"
          description: 중복 확인할 닉네임
      responses:
        "200":
          description: 닉네임 사용 가능 여부 응답
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                        example: "available_nickname"
                      data:
                        type: object
                        properties:
                          result:
                            type: boolean
                            example: true
                  - type: object
                    properties:
                      message:
                        type: string
                        example: "already_exist_nickname"
                      data:
                        type: object
                        properties:
                          result:
                            type: boolean
                            example: false
        "400":
          description: 잘못된 요청 (닉네임이 빈 문자열이거나 특수문자 포함)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "invalid_input"
                  data:
                    type: object
                    properties:
                      error:
                        type: string
                        example: "닉네임은 빈 문자열이거나 특수문자를 포함할 수 없습니다."
