name: Deploy Spring Boot App

on:
    push:
        branches:
            - main
            - develop

jobs:
    deploy-dev:
        if: github.ref == 'refs/heads/develop'
        uses: ./.github/workflows/deploy-common.yml
        with:
            environment: dev
            cors_origin: https://dev.warab.store
            redirect_uri: https://dev.api.warab.store/login/oauth2/code/kakao
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            DATABASE_USER: ${{ secrets.DATABASE_USER }}
            DATABASE_PASSWD: ${{ secrets.DATABASE_PASSWD }}
            KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
            KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
            JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
            SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
            SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
            SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT_NAME: ${{ secrets.SENTRY_PROJECT_NAME }}
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            DEPLOY_REPO_PAT: ${{ secrets.DEPLOY_REPO_PAT }}
            REDIS_HOST: ${{ secrets.REDIS_HOST }}
            REDIS_PORT: ${{ secrets.REDIS_PORT }}
            REDIS_PASSWD: ${{ secrets.REDIS_PASSWD }}

    deploy-prod:
        if: github.ref == 'refs/heads/main'
        uses: ./.github/workflows/deploy-common.yml
        with:
            environment: prod
            cors_origin: https://warab.store
            redirect_uri: https://api.warab.store/login/oauth2/code/kakao
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
            DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
            DATABASE_USER: ${{ secrets.PROD_DATABASE_USER }}
            DATABASE_PASSWD: ${{ secrets.PROD_DATABASE_PASSWD }}
            KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
            KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
            JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
            SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
            SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
            SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT_NAME: ${{ secrets.SENTRY_PROJECT_NAME }}
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            DEPLOY_REPO_PAT: ${{ secrets.DEPLOY_REPO_PAT }}
            REDIS_HOST: ${{ secrets.REDIS_HOST }}
            REDIS_PORT: ${{ secrets.REDIS_PORT }}
            REDIS_PASSWD: ${{ secrets.REDIS_PASSWD }}


