name: Deploy Spring Boot App

on:
    push:
        branches:
            - main
            - develop

jobs:
    deploy-dev:
        if: github.ref == 'refs/heads/develop'
        uses: ./.github/workflows/deploy-common.yml
        with:
            environment: dev
            cors_origin: https://dev.warab.store
        environment: dev

    deploy-prod:
        if: github.ref == 'refs/heads/main'
        uses: ./.github/workflows/deploy-common.yml
        with:
            environment: prod
            cors_origin: https://warab.store
        environment: prod
